<!-- main wrapper start -->
<div class="main-wrapper" id="main-wrapper">
    <!-- breadcrumb start -->
    <section class="section-wrapper breadcrumb-wrapper" id="breadcrumb-wrapper">
        <div class="sqaure">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="breadcrumb-block">
                            <h2 class="glowIn">Privacy policy</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb end -->
    <!-- Privacy page start -->
    <section class="section-wrapper terms-page">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12">
                    <div class="condition-block" data-aos="fade-up">
                        Your privacy is our priority. For that reason, we have developed a comprehensible Privacy Policy that explains in detail how we collect, use, communicate and disclose your personal data. Below is our privacy policy at 247cookrecipes.com We are committed to conducting our business in compliance with the aforementioned principles with the chief objective of ensuring that the security and confidentiality of our customers’ personal data is protected and maintained.<br><br>
                        • Before and throughout the collection of personal data we will always identify the reasons for which your personal information is being<br>
                        • We collect and use personal information with the sole aim of fulfilling the purposes specified by ((SITE_NAME)) as well as for other directly related purposes.<br>
                        • We only retain personal data for as long as it is necessary in order to fulfil these purposes.<br>
                        • We only use lawful means to collect personal information and, where appropriate, with the knowledge and/or consent of the individual concerned.<br>
                        • All personal information collected must be relevant to the purposes for which it was intended, and, to the extent necessary for said purposes, should be accurate, complete, and up-to-date.<br>
                        • We will protect personal data with the help of reasonable security measures against loss or theft, as well as against unauthorized access, disclosure, copying, exploitation or modification.<br>
                        • We will make fully available to our customers any information about our policies and practices that is related to the management of personal data.<br><br>
                        We are committed to conducting our business in compliance with the aforementioned principles with the chief objective of ensuring that the security and confidentiality of our customers’ personal data is protected and maintained.<br><br>
                        <h1>What personal data is gathered from you?</h1>
                        When you access, register, participate, create an account or in any other way make use of our services, we may collect personal data about you. The nature of the data we collect is defined by the circumstances and services you use, but may consist of the following: <br><br>
                        <b>Personal Information generated by the User</b><br>
                        Your purchase references in connection to ads and/or campaigns<br>
                        • IP address<br>
                        We also collect data regarding your use of our services through cookies and related technologies.<br><br>
                        <b>Personal data collected from third parties</b><br>
                        On occasion, we can supplement the data collected from our customers with data received from third parties as well as through your use of products, websites or other services offered by Randomness LTD. This might include information from third parties that handle our payment processing solutions. <br><br>
                        <b>Why we collect your Personal Data?</b><br>
                        Your personal information is processed for the following purposes: <br><br>
                        <b>A) In order to comply with our contractual relationship:</b><br>
                        • For the purpose of handling payments and delivering order and invoice information in a safe and correct manner<br>
                        • To keep track of all your purchases and ensure that you receive the services you have paid for<br>
                        • To deliver important information regarding your subscription, account and/or purchase of our Services<br>
                        • To inform you about important changes in our Services<br>
                        • To provide news, offers, products or services that you may request from us <br><br>
                        <b>B) For legitimate purposes:</b><br>
                        • To share your data within Randomness LTD for administrative reasons or to facilitate the delivery of our Services to you<br>
                        • To use relevant IP address or other information required to block unauthorized use of our Services in order to protect our Services and enforce compliance with our Terms and Conditions<br>
                        • To provide necessary data in the case of a merger and acquisition process for business and/or strategic management purposes.<br>
                        • To provide you with news, offers, products or services that we believe may be of interest to you, including focused advertising based on your interests.<br>
                        • For analytical as well as statistical purposes<br>
                        • To establish, exercise or protect legal requirements <br><br>
                        <b>C) We may also, if needed, process your personal information to comply with a legal obligation or requirement issued by an authority. What legal basis in GDPR do we base the processing of your personal data on?</b><br>
                        • point (A) is required in order to conclude and fulfil our contractual obligations;<br>
                        • point (B) is required to satisfy our interests in managing, developing, safeguarding and marketing our Services from a business and strategic perspective;<br>
                        • point (C) is only effectuated with your expressed consent<br>
                        • point (D) is required in order to comply with current legal obligations; <br><br>
                        <b>Are you Obligated to Provide Your Personal Data?</b><br>
                        All personal information that we may request from you and which is marked as “mandatory” is required for us to be able to provide our Services (for contractual, administrative, legal, technical or similar purposes) in a safe and correct manner.<br>
                        There is, however, certain personal data that will only be required if you use specific features, buy optional elements of our Service, or request access to special resources, promotions, offers, programs or otherwise related services from Randomness LTD or our marketing partners.<br>
                        You will be informed about this before we start collecting such personal information. <br><br>
                        <b>Who Can We Share Your Personal Data With?</b>
                        <i>Group transfers</i><br>
                        We can disclose your personal information to other areas within Randomness LTD if deemed necessary for administrative purposes or in order to provide you with our Services. If we have your consent, we may also disclose your personal data within Randomness LTD for marketing purposes. Products within Randomness LTD that access your personal data must comply with the practices set forth in this Privacy Policy.<br>
                        <i>The partners, sponsors and advertisers</i><br>
                        We may share your personal data with our partners and sponsors. In addition, we may also disclose your personal information to any of our collaborators and advertisers, but will only do so with your expressed consent.<br>
                        We may also use certain information to oversee the use of our Services. The purpose for this is to continuously improve and develop our Services. Occasionally, we will make such aggregated data available to certain third parties, such as partners and/or advertisers. This does not include personal information.<br>
                        <i>Third parties for security measures or other legitimate purposes</i><br>
                        We may share your personal information with third parties if should consider it necessary in order to:<br>
                        • Comply with legal obligations, including court orders, government requests, applicable search warranties, or other requests we are bound to by law;<br>
                        • Protect our rights and/or property, as well as the safety of our customers and/or employees;<br>
                        • Protect our Randomness LTD against fraudulent, malicious, unauthorized or illegal use of our Services, Devices, Network and User Data;<br>
                        • Promote or defend our Services against complaints or legal claims, administrative procedures and similar demands;<br>
                        • Assess credit risk, issue business reports or receive payment for our Services<br>
                        • As part of a merger and/or aggregation, provided that the potential acquirer or seller agrees to respect your personal information and process it in compliance with our Privacy Policy;<br>
                        • To external supervisors and auditors<br><br>
                        <b>Where is Your Personal Information processed?</b><br>
                        All personal data collected from you may be transferred to and stored outside the European Economic Area (“EEA”). This includes destinations not encompassed by the European Commission regarding an adequate level of protection for processing personal data. It may be disclosed to other products within Randomness LTD, managed by Randomness LTD employees or employees working for suppliers of Randomness LTD outside the EEA. Such staff can be involved in processing your order, payment information and/or performing support services for Randomness LTD, among other services. All reasonable precautions are taken to ensure that your personal data is handled in a safe manner and in accordance with our Privacy Policy, taking appropriate measures to protect all your personal information. For more information about our Privacy Policy or to obtain a copy of these measures, please contact us using the contact information found at the bottom of this Privacy Policy.<br><br>
                        <b>How Long is Your Personal Data Stored with us?</b><br><br>
                        <p>Type of data Significance Deletion deadline
                            User data Information about how you use our services and your product orders Until the account is deleted (is processed in 5 years)
                            Customer service data Customer service data is information that you provide when you are in contact with ((SITE_NAME))'s customer service and voice recordings made for educational purposes. 3 years (call logs and text dialogs)
                            1 month (voice recordings)
                            Account information Information regarding your account, i.e. username, password and order information made in the ((SITE_NAME)) service. Until deletion of account
                            Transaction data Information about transactions effectuated through your account 10 years
                        </p>
                        <b>How can we Secure Your Personal Data?</b><br>
                        Protecting your personal information is vital to us and a primary concern at Randomness LTD. All personal data provided by you is stored on secure servers and we follow strict procedures in order to safeguard all data against abuse, unauthorized access, loss, disclosure or deletion/destruction. All payment transactions are encrypted with the help of industry standard technology and subject to PCI security standards.<br>
                        Although we work hard to safeguard your personal information, we are unable to fully guarantee that our internal security measures will prevent all unauthorized attempts to use, access or disclose your personal information. That said, we have developed specific safety plans, including strategies for managing any breach of data security, that are implemented if and when such a physical or technical incident should occur in order to handle the issue in a timely fashion and restrict any negative effect that said incident might cause.<br><br>
                        <b>How do you Access Your Own Personal Information?</b><br>
                        We understand that there are times when you will need additional information from us regarding your personal data and how it is processed. Other times you may wish to update the personal information you have already provided for us. With respect to the management of personal data, you are entitled to the following:<br>
                        You have the right to access all your personal information. You have the right to be informed by us when and if we process personal data about you and, if so, to access such data.<br>
                        You have the right to have personal information corrected and/or updated: If you should find that the personal information we have stored about you is incorrect, you have the full right to request an update and/or correction of such personal data. <br>
                        You have the right to have your personal information deleted: Under certain circumstances, for instance if your personal data has been acquired or processed in a fraudulent or illegal manner or if you have withdrawn your consent (when the processing of personal data is based on prior customer consent), you have the right to request that we delete your personal information. <br>
                        You have the right to restrict the processing of personal information: under certain circumstances, for instance if you should disagree with the accuracy of your personal information or if you should object to our legitimate purpose for processing your personal data, you have the right to request that we restrict the use and/or processing of your personal data until an appropriate solution has been found.<br>
                        You have the right to object to the processing of your personal data: under certain circumstances, for instance if you should disagree with our legitimate interest in processing your personal data, you have the right to contend such processing.<br>
                        You have the right to data portability: If your personal data is being processed automatically with your consent or on the basis of our contractual relationship, you are entitled to request a copy of your personal data in a machine-readable format for the transmission to an external data controller.<br>
                        You have the right to file a complaint with your supervisory authority: In case you should disagree with the manner in which we process your personal data, you may file a complaint with your supervisory authority.<br>
                        If we should process your personal information on the basis of your prior consent, you are still entitled to withdraw such consent at any time (it will not affect the data that has already been processed prior to your withdrawal) by contacting us or by updating your settings.<br>
                        If you wish to make a request, please contact us by using the contact details at the bottom of this document. We will do our best to respond to your request within 30 days of receiving it. If we are unable to comply with your request within 30 days, we will inform you of the situation, the reason for such a delay and when we expect to be able to fulfil your request.
                        You can change your contact preferences on the “Settings” page if you wish to limit the types of information you receive from us. You can also do this by contacting us directly at contact@((SITE_NAME)) or by calling +44 321 2332233.<br><br>
                        <h1>Changes To This Privacy Policy</h1>
                        <br>
                        Our Privacy Policy may be amended periodically. Be sure to review the latest version of this policy from time to time. Any changes to our Privacy Policy are disclosed here. If the changes are substantial we will inform you of this through an E-mail message. If changes to this Privacy Policy are made in a way that affects the manner in which we process your personal data we will inform you about the choices available to you as a result of these changes. We also keep previous versions of this Privacy Policy archived for your review.<br><br>
                        <h3>((SITE_NAME)) owner information</h3>
                        <br>For further information about our Terms &amp; Conditions or to enquire about any other unanswered issues or questions, please contact us through the information details below. ((SITE_NAME)) is owned and operated by: <br>
                        <p>Random<br>
                            CRN: RR4566545<br>
                            random 23<br>
                            4000<br>
                            Odense<br>
                            random<br>
                            Europe<br>
                            support@((SITE_NAME))<br>
                            +44 00000000
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Privacy page end -->
</div>
<!-- main wrapper end -->
<!-- Once time model open start -->
<div id="myModal" class="modal fade modeltime" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close modeltimeclose" data-dismiss="modal"><img src="assets/images/icon/close.svg" alt="close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="model-wrapper">
                            <div class="model-description">
                                <img src="assets/images/icon/logo.svg" alt="logo">
                                <h2>Welcome</h2>
                                <p>Hendrerit amet tortor vulputate erat vitae accumsan. Sed augue iaculis ullamcorper enim mauris. Quis varius id tristique euismod. Sem egestas mauris id amet hac lacinia nisi morbi nibh. Ipsum elementum pulvinar vestibulum convallis nec hendrerit fames mollis</p>
                                <p>Agree that you have read our <a href="terms-services.html">Terms & condition</a>, <a href="privacy-policy.html">Privacy policy</a> & <a href="cookie-policy.html">Cookie policy</a> by pressing continue</p>
                                <div class="theme-button">
                                    <a href="#" data-dismiss="modal" class="submit-btn">Continue</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Once time model open end -->